db_data = [{'id': 1, 'code': 'vk', 'name': 'Вконтакте',
            'search_names': 'Вконтактеvk.comVK,ВК,Вконтакте,DR,Drjynfrnt,Млщтефлеу,Vkontakte'},
           {'id': 2, 'code': 'wa', 'name': 'Whatsapp',
            'search_names': 'Whatsapp,ВА,WA,вотсап,ватсап,вотс ап,ватс ап,whatsup,wotsup,djncfg,dfncfg'},
           {'id': 3, 'code': 'vi', 'name': 'Viber', 'search_names': 'Viber,вайбер,dfqth,viber'},
           {'id': 4, 'code': 'ds', 'name': 'Discord', 'search_names': 'Discord,Дискорд,вшысщкв,lbcrjhl'},
           {'id': 5, 'code': 'hb', 'name': 'Twitch', 'search_names': 'Twitch'},
           {'id': 6, 'code': 'md', 'name': 'Банки', 'search_names': 'Банки'},
           {'id': 7, 'code': 'bz', 'name': 'Blizzard',
            'search_names': 'Blizzard,战网暴雪,warcraft,battle,battenet,battlenet'},
           {'id': 8, 'code': 'qz', 'name': 'Faceit', 'search_names': 'Faceit'},
           {'id': 9, 'code': 'ng', 'name': 'FunPay', 'search_names': 'FunPay'},
           {'id': 10, 'code': 'lf', 'name': 'TikTok/Douyin',
            'search_names': 'TikTok/Douyin,тик ток,nbr njr,ешл ещл,douyin,抖音'},
           {'id': 11, 'code': 'tg', 'name': 'Telegram',
            'search_names': 'Telegram,TG,ТГ,телеграм,телеграмм,ntktuhfv,ntktuhfvv,телега,ntktuf'},
           {'id': 12, 'code': 'fu', 'name': 'Snapchat', 'search_names': 'Snapchat,cyfgxfn,снапчат,ытфзсрфе'},
           {'id': 13, 'code': 'fb', 'name': 'facebook',
            'search_names': 'facebook,фейсбук,atqc,АИ,FB,facebook,meta,мета'},
           {'id': 14, 'code': 'tn', 'name': 'LinkedIN',
            'search_names': 'LinkedIN,kbyrtl,kbyrbl,kbyrtlby,линкед,линкид,линкидин'},
           {'id': 15, 'code': 'ig', 'name': 'Instagram+Threads',
            'search_names': 'Instagram+Threadsинстаграм,bycnfuhfv,штыефпкф,trends,threads,трендс,тренды,мета,meta'},
           {'id': 16, 'code': 'ok', 'name': 'Одноклассники',
            'search_names': 'Одноклассникиok.ru,OK,ЗЛ,ОК,jlyjrkfcybrb,однокласники'},
           {'id': 17, 'code': 'qv', 'name': 'Badoo', 'search_names': 'Badoo'},
           {'id': 18, 'code': 'bl', 'name': 'BIGO LIVE', 'search_names': 'BIGO LIVE,биго лайв,ишпщ дшму,,bujkfqd'},
           {'id': 19, 'code': 'oi', 'name': 'Tinder', 'search_names': 'Tinder,тиндер,nbylth,ештвук'},
           {'id': 20, 'code': 'oj', 'name': 'LoveRu', 'search_names': 'LoveRu'},
           {'id': 21, 'code': 'qs', 'name': 'МирЗнакомств', 'search_names': 'МирЗнакомств'},
           {'id': 22, 'code': 'fy', 'name': 'Mylove', 'search_names': 'Mylove,vfqkfd,майлав,ьндщму'},
           {'id': 23, 'code': 'hw', 'name': 'Alipay/Alibaba/1688',
            'search_names': 'Alipay/Alibaba/1688,алипей,фдшзфн,fkbgtq,168商城,168,168com,168com,168сщь,168rjv,1688,1688com,fkb,fkb’rghtc,fkbtrcghtc,алибаба,али баба,фдшузкуыы,фдш ифиф,фдш учзкуы,阿里快递,168商城,168,168com,168com,168сщь,168rjv,1688,1688com,阿里巴巴，alibaba,alibabacom,aliexpress,阿里爸爸,阿里八八,阿丽巴巴'},
           {'id': 24, 'code': 'ya', 'name': 'Яндекс', 'search_names': 'ЯндексYandex,yandex,zyltrc'},
           {'id': 25, 'code': 'afo', 'name': 'KION ', 'search_names': 'KION '},
           {'id': 26, 'code': 'go', 'name': 'Google,youtube,Gmail',
            'search_names': 'Google,youtube,Gmail,google,youtube,gmail,гугл,ютуб,ютьюб,гмейл,джмейл'},
           {'id': 27, 'code': 'nf', 'name': 'Netflix', 'search_names': 'Netflix,нетфликс,ytnakbrc,туеадшч'},
           {'id': 28, 'code': 'dh', 'name': 'eBay', 'search_names': 'eBay,ебей,уифн'},
           {'id': 29, 'code': 'ts', 'name': 'PayPal', 'search_names': 'PayPal,gtqgfk,пейпал'},
           {'id': 30, 'code': 'xn', 'name': 'Familia', 'search_names': 'Familia'},
           {'id': 31, 'code': 'nc', 'name': 'Payoneer', 'search_names': 'Payoneer'},
           {'id': 32, 'code': 'mb', 'name': 'Yahoo', 'search_names': 'Yahoo,яху,нфрщщ,ze'},
           {'id': 33, 'code': 'rc', 'name': 'Skype', 'search_names': 'Skype'},
           {'id': 34, 'code': 'mm', 'name': 'Microsoft',
            'search_names': 'Microsoftmicro,микро,майкрософт,микрософт,ьшскщыщае,soft,софт'},
           {'id': 36, 'code': 'ui', 'name': 'RuTube', 'search_names': 'RuTube'},
           {'id': 38, 'code': 'ma', 'name': 'Mail.ru', 'search_names': 'Mail.ru,почта,мейл,ьфшд,мейлру,ьфшдкг'},
           {'id': 39, 'code': 'uu', 'name': 'Wildberries', 'search_names': 'Wildberries,dfqkl,вайлдбериз,цфшдвбериз'},
           {'id': 40, 'code': 'sg', 'name': 'OZON', 'search_names': 'OZON,озин,озон,jpjy'},
           {'id': 41, 'code': 'mt', 'name': 'Steam', 'search_names': 'Steam,cnbv,стим'},
           {'id': 42, 'code': 'ym', 'name': 'Юла', 'search_names': 'Юлаyoula.ru,Youla,Yula,ula'},
           {'id': 43, 'code': 'av', 'name': 'avito', 'search_names': 'avito,авито,овито,avito,fdbnj,авита'},
           {'id': 44, 'code': 'adr', 'name': 'Boosty', 'search_names': 'Boosty'},
           {'id': 45, 'code': 'hz', 'name': 'Drom', 'search_names': 'Dromдром'},
           {'id': 46, 'code': 'be', 'name': 'СберМегаМаркет', 'search_names': 'СберМегаМаркет'},
           {'id': 47, 'code': 'yh', 'name': 'hh', 'search_names': 'hh'},
           {'id': 48, 'code': 'ajc', 'name': 'Почта России', 'search_names': 'Почта России'},
           {'id': 49, 'code': 'ke', 'name': 'Эльдорадо', 'search_names': 'Эльдорадоeldorado'},
           {'id': 50, 'code': 'jc', 'name': 'IVI', 'search_names': 'IVI'},
           {'id': 51, 'code': 'jr', 'name': 'Самокат', 'search_names': 'Самокат,samokat,ыфьщлфе,cfvjrfn'},
           {'id': 52, 'code': 'aeh', 'name': 'Аптека Апрель', 'search_names': 'Аптека Апрель'},
           {'id': 53, 'code': 'sl', 'name': 'СберАптека', 'search_names': 'СберАптека'},
           {'id': 54, 'code': 'xm', 'name': 'Лэтуаль', 'search_names': 'Лэтуаль'},
           {'id': 55, 'code': 'aca', 'name': 'Sunlight', 'search_names': 'Sunlight'},
           {'id': 56, 'code': 'bv', 'name': 'Metro', 'search_names': 'Metro'},
           {'id': 57, 'code': 'dj', 'name': 'LUKOIL-AZS', 'search_names': 'LUKOIL-AZS'},
           {'id': 58, 'code': 'rj', 'name': 'Детский мир', 'search_names': 'Детский мир'},
           {'id': 59, 'code': 'wx', 'name': 'Apple', 'search_names': 'Appleэпл'},
           {'id': 60, 'code': 'bd', 'name': 'X5ID',
            'search_names': 'X5IDпятёрочка,5ка,5ka,rfhectkm,карусель,впрок,vprok,5post,пятерочка,перекрёсток,Перекресток,около,ЭкспрессСкан,Пятёрочка Доставка,Vprokru,Пакет,Пятёрочка Налету,5пост'},
           {'id': 61, 'code': 'ip', 'name': 'Burger King',
            'search_names': 'Burger King,бургеркинг,бургер кинг,игкпуклштп,,ehuthrbyu'},
           {'id': 62, 'code': 'br', 'name': 'Вкусно и Точка', 'search_names': 'Вкусно и Точка'},
           {'id': 63, 'code': 'sd', 'name': 'dodopizza', 'search_names': 'dodopizzaдодо'},
           {'id': 64, 'code': 'pn', 'name': 'CoffeeLike', 'search_names': 'CoffeeLike'},
           {'id': 65, 'code': 'ty', 'name': 'Окей', 'search_names': 'Окей'},
           {'id': 66, 'code': 'dz', 'name': 'Dominos Pizza', 'search_names': 'Dominos Pizzaдоминос'},
           {'id': 67, 'code': 'adz', 'name': 'Шоколадница', 'search_names': 'Шоколадница'},
           {'id': 68, 'code': 'mg', 'name': 'Магнит', 'search_names': 'МагнитMagnit,magnit,vfuybn,ьфптше'},
           {'id': 69, 'code': 'tk', 'name': 'МВидео', 'search_names': 'МВидеоmvideo'},
           {'id': 70, 'code': 'ahl', 'name': 'Maxim', 'search_names': 'Maxim'},
           {'id': 71, 'code': 'yk', 'name': 'СпортМастер',
            'search_names': 'СпортМастер,cgjhnvfcnth,спортмастер,ызщкеьфыеук'},
           {'id': 72, 'code': 'rd', 'name': 'Lenta', 'search_names': 'Lenta,лента'},
           {'id': 73, 'code': 'sb', 'name': 'Lamoda', 'search_names': 'Lamoda'},
           {'id': 74, 'code': 'agt', 'name': 'Uralairlines', 'search_names': 'Uralairlines'},
           {'id': 75, 'code': 'jp', 'name': 'Rbt', 'search_names': 'Rbt'},
           {'id': 76, 'code': 'ua', 'name': 'BlaBlaCar', 'search_names': 'BlaBlaCar,бла бла кар,блаблакар,идфидфкар'},
           {'id': 77, 'code': 'sh', 'name': 'ВкусВилл', 'search_names': 'ВкусВиллVkusvill'},
           {'id': 78, 'code': 'ub', 'name': 'Uber', 'search_names': 'Uber,убер,юбер,такси'},
           {'id': 79, 'code': 'st', 'name': 'Ашан', 'search_names': 'АшанAuchan'},
           {'id': 80, 'code': 'da', 'name': 'MTS CashBack', 'search_names': 'MTS CashBackмтс'},
           {'id': 81, 'code': 'tw', 'name': 'Twitter',
            'search_names': 'Twitter,твитер,твиттер,твит,twiter,twit,elon musk,илон маск,bkjy vfcr'},
           {'id': 84, 'code': 'tc', 'name': 'Rambler', 'search_names': 'Ramblerрамблер,кфьидук'},
           {'id': 85, 'code': 'am', 'name': 'Amazon', 'search_names': 'Amazon,fvfpjy,амазон,фьфящт'},
           {'id': 86, 'code': 'wb', 'name': 'WeChat', 'search_names': 'WeChat,вичат,цусрфе,dbxfn'},
           {'id': 87, 'code': 'fd', 'name': 'Mamba, MeetMe', 'search_names': 'Mamba, MeetMeMamba,vfv,мамба'},
           {'id': 88, 'code': 'afa', 'name': 'CDEK', 'search_names': 'CDEK'},
           {'id': 89, 'code': 'tx', 'name': 'Bolt', 'search_names': 'Bolt,,jkn,болт,ищде'},
           {'id': 90, 'code': 'dt', 'name': 'Delivery Club',
            'search_names': 'Delivery Club,деливери,деливериклаб,деливери клаб,ltkbdthb,ltkbdthb rkf,доставка,вудшмукн,Delivery,Delivery club,club'},
           {'id': 91, 'code': 'il', 'name': 'IQOS', 'search_names': 'IQOSайкос'},
           {'id': 92, 'code': 'qr', 'name': 'MEGA', 'search_names': 'MEGA,мега,ьупф,vtuf'},
           {'id': 93, 'code': 'ta', 'name': 'Wink', 'search_names': 'Wink'},
           {'id': 94, 'code': 'uk', 'name': 'Airbnb', 'search_names': 'Airbnb,fbh,аир,аирбнб'},
           {'id': 95, 'code': 'cy', 'name': 'РСА',
            'search_names': 'РСА,ABSOLUTINS,ACKO,CK_MAKC,egarant,EUROINS,Ingosstrakh,PCA,reninsru,RGSru,SOGAZ,Soglasie,ugoria,VSK,reso'},
           {'id': 96, 'code': 'ae', 'name': 'myGLO', 'search_names': 'myGLO'},
           {'id': 98, 'code': 'bh', 'name': 'Uteka', 'search_names': 'Uteka'},
           {'id': 99, 'code': 'kf', 'name': 'Weibo', 'search_names': 'Weibo'},
           {'id': 100, 'code': 'ah', 'name': 'EscapeFromTarkov', 'search_names': 'EscapeFromTarkov'},
           {'id': 101, 'code': 'qq', 'name': 'Tencent QQ', 'search_names': 'Tencent QQ,тенсент,кью кью,ntyctyn'},
           {'id': 102, 'code': 'adw', 'name': 'Профи', 'search_names': 'Профи'},
           {'id': 103, 'code': 'sz', 'name': 'Pivko24', 'search_names': 'Pivko24'},
           {'id': 104, 'code': 'ol', 'name': 'KazanExpress', 'search_names': 'KazanExpress'},
           {'id': 105, 'code': 'me', 'name': 'Line messenger',
            'search_names': 'Line messenger,Лайн,лайн месенджер,лине,kfqy'},
           {'id': 106, 'code': 'rl', 'name': 'inDriver', 'search_names': 'inDriver'},
           {'id': 107, 'code': 'xr', 'name': 'Tango', 'search_names': 'Tango'},
           {'id': 108, 'code': 'sv', 'name': 'Dostavista', 'search_names': 'Dostavistaдостависта'},
           {'id': 109, 'code': 'xe', 'name': 'GalaxyChat', 'search_names': 'GalaxyChat'},
           {'id': 110, 'code': 'ady', 'name': 'ТОКИО-CITY', 'search_names': 'ТОКИО-CITY'},
           {'id': 111, 'code': 'zs', 'name': 'Bilibili', 'search_names': 'Bilibili'},
           {'id': 112, 'code': 'iq', 'name': 'icq', 'search_names': 'icq,fqcbrm,шсй'},
           {'id': 113, 'code': 'xa', 'name': 'УлыбкаРадуги', 'search_names': 'УлыбкаРадуги'},
           {'id': 114, 'code': 'bo', 'name': 'Wise', 'search_names': 'Wise'},
           {'id': 115, 'code': 'qf', 'name': 'RedBook', 'search_names': 'RedBook'},
           {'id': 116, 'code': 'ahn', 'name': 'Рив Гош', 'search_names': 'Рив Гош'},
           {'id': 117, 'code': 'bw', 'name': 'Signal', 'search_names': 'Signal'},
           {'id': 118, 'code': 'pm', 'name': 'AOL', 'search_names': 'AOL,fjk,аол'},
           {'id': 119, 'code': 'abn', 'name': 'Namars', 'search_names': 'Namars'},
           {'id': 120, 'code': 'of', 'name': 'urent/jet/RuSharing', 'search_names': 'urent/jet/RuSharing'},
           {'id': 121, 'code': 'amn', 'name': 'constitutioner', 'search_names': 'constitutioner'},
           {'id': 122, 'code': 'aiw', 'name': 'СушиВёсла', 'search_names': 'СушиВёсла'},
           {'id': 123, 'code': 'akf', 'name': 'Ollis', 'search_names': 'Ollis'},
           {'id': 124, 'code': 'afp', 'name': 'VFS GLOBAL', 'search_names': 'VFS GLOBAL'},
           {'id': 125, 'code': 'ahm', 'name': 'BRO', 'search_names': 'BRO'},
           {'id': 126, 'code': 'adx', 'name': 'BusyFly', 'search_names': 'BusyFly'},
           {'id': 127, 'code': 'pj', 'name': 'Podeli', 'search_names': 'Podeli'},
           {'id': 128, 'code': 'oo', 'name': 'LigaPro', 'search_names': 'LigaPro'},
           {'id': 129, 'code': 'lz', 'name': 'Things', 'search_names': 'Things'},
           {'id': 130, 'code': 'es', 'name': 'iQIYI', 'search_names': 'iQIYI'},
           {'id': 131, 'code': 'io', 'name': 'ЗдравСити', 'search_names': 'ЗдравСити'},
           {'id': 132, 'code': 'ake', 'name': 'DIKIDI', 'search_names': 'DIKIDI'},
           {'id': 133, 'code': 'aiy', 'name': 'nloto', 'search_names': 'nloto'},
           {'id': 134, 'code': 'yd', 'name': '米画师Mihuashi', 'search_names': '米画师Mihuashi'},
           {'id': 135, 'code': 'vl', 'name': 'Ортека', 'search_names': 'Ортека'},
           {'id': 136, 'code': 'aiz', 'name': 'Brevo', 'search_names': 'Brevo'},
           {'id': 137, 'code': 'aji', 'name': 'МИГРАНТ СЕРВИС', 'search_names': 'МИГРАНТ СЕРВИС'},
           {'id': 138, 'code': 'vq', 'name': 'LadyMaria', 'search_names': 'LadyMaria'},
           {'id': 139, 'code': 'wy', 'name': 'Yami', 'search_names': 'Yami'},
           {'id': 140, 'code': 'xo', 'name': 'Notifire', 'search_names': 'Notifire'},
           {'id': 141, 'code': 'yf', 'name': 'Citymobil', 'search_names': 'Citymobil,cbnbvj,ситимобил,сшеньщишд'},
           {'id': 142, 'code': 'mz', 'name': 'Zolushka', 'search_names': 'Zolushka'},
           {'id': 143, 'code': 'nw', 'name': 'Ximalaya', 'search_names': 'Ximalaya'},
           {'id': 144, 'code': 'ba', 'name': 'Expressmoney', 'search_names': 'Expressmoney'},
           {'id': 145, 'code': 'ain', 'name': 'SpaceWeb', 'search_names': 'SpaceWeb'},
           {'id': 146, 'code': 'aek', 'name': 'EnerGO', 'search_names': 'EnerGO'},
           {'id': 147, 'code': 'ye', 'name': 'ZaleyCash', 'search_names': 'ZaleyCash'},
           {'id': 148, 'code': 'xc', 'name': 'SynotTip', 'search_names': 'SynotTip'},
           {'id': 149, 'code': 'yo', 'name': 'Amasia', 'search_names': 'Amasia'},
           {'id': 150, 'code': 'abm', 'name': 'Утконос', 'search_names': 'Утконос'},
           {'id': 151, 'code': 'de', 'name': 'Karusel', 'search_names': 'Karuselкарусель'},
           {'id': 152, 'code': 'um', 'name': 'Belwest', 'search_names': 'Belwest'},
           {'id': 153, 'code': 'ahz', 'name': 'Кузбасс Онлайн', 'search_names': 'Кузбасс Онлайн'},
           {'id': 154, 'code': 'lm', 'name': 'FarPost', 'search_names': 'FarPost'},
           {'id': 155, 'code': 'cu', 'name': '炙热星河', 'search_names': '炙热星河'},
           {'id': 156, 'code': 'ao', 'name': 'UU163', 'search_names': 'UU163'},
           {'id': 157, 'code': 'ahx', 'name': 'Bitrue', 'search_names': 'Bitrue'},
           {'id': 158, 'code': 'xp', 'name': 'MonetaRu', 'search_names': 'MonetaRu'},
           {'id': 159, 'code': 'aes', 'name': 'Золотое Яблоко', 'search_names': 'Золотое Яблоко'},
           {'id': 160, 'code': 'js', 'name': 'Голос', 'search_names': 'ГолосGolosZa'},
           {'id': 161, 'code': 'xx', 'name': 'Joyride', 'search_names': 'Joyride'},
           {'id': 162, 'code': 'vj', 'name': 'Stormgain', 'search_names': 'Stormgain'},
           {'id': 163, 'code': 'ut', 'name': 'Энергобум', 'search_names': 'Энергобум'},
           {'id': 164, 'code': 'ja', 'name': 'Weverse', 'search_names': 'Weverse'},
           {'id': 165, 'code': 'uq', 'name': 'TopDetal', 'search_names': 'TopDetal'},
           {'id': 166, 'code': 'ps', 'name': 'Zdorov', 'search_names': 'Zdorov'},
           {'id': 167, 'code': 'aeg', 'name': 'Flowwow', 'search_names': 'Flowwow'},
           {'id': 168, 'code': 'nj', 'name': 'FreshKarta', 'search_names': 'FreshKarta'},
           {'id': 169, 'code': 'ux', 'name': 'Домовой', 'search_names': 'Домовой'},
           {'id': 170, 'code': 'hg', 'name': 'Switips', 'search_names': 'Switips'},
           {'id': 171, 'code': 'en', 'name': 'Hermes', 'search_names': 'Hermes'},
           {'id': 172, 'code': 'iw', 'name': 'MyLavash', 'search_names': 'MyLavash'},
           {'id': 173, 'code': 'tz', 'name': 'Лейка', 'search_names': 'Лейка'},
           {'id': 174, 'code': 'gb', 'name': 'YouStar', 'search_names': 'YouStar'},
           {'id': 175, 'code': 'afl', 'name': 'Vsesmart', 'search_names': 'Vsesmart'},
           {'id': 176, 'code': 'ce', 'name': 'mosru', 'search_names': 'mosru,мосру,мос ру,ьщыкг,vjche'},
           {'id': 177, 'code': 'aat', 'name': 'TamTam', 'search_names': 'TamTam'},
           {'id': 178, 'code': 'vb', 'name': 'Кораблик', 'search_names': 'Кораблик'},
           {'id': 179, 'code': 'lv', 'name': 'Megogo', 'search_names': 'Megogo'},
           {'id': 180, 'code': 'bi', 'name': '勇仕网络Ys4fun', 'search_names': '勇仕网络Ys4fun'},
           {'id': 181, 'code': 'pp', 'name': 'Huya', 'search_names': 'Huya'},
           {'id': 182, 'code': 'wu', 'name': 'PrivetMir', 'search_names': 'PrivetMir'},
           {'id': 183, 'code': 'ro', 'name': 'PingCode', 'search_names': 'PingCode'},
           {'id': 184, 'code': 'afv', 'name': 'Джилекс', 'search_names': 'Джилекс'},
           {'id': 185, 'code': 'jy', 'name': 'Sorare', 'search_names': 'Sorare'},
           {'id': 186, 'code': 'jv', 'name': 'Consultant', 'search_names': 'Consultant'},
           {'id': 187, 'code': 'adq', 'name': 'Uzum', 'search_names': 'Uzum'},
           {'id': 188, 'code': 'aif', 'name': 'Royal Canin', 'search_names': 'Royal Canin'},
           {'id': 189, 'code': 'rq', 'name': 'AptekiPlus', 'search_names': 'AptekiPlus'},
           {'id': 190, 'code': 'bd', 'name': 'X5ID',
            'search_names': 'X5IDпятёрочка,5ка,5ka,rfhectkm,карусель,впрок,vprok,5post,пятерочка,перекрёсток,Перекресток,около,ЭкспрессСкан,Пятёрочка Доставка,Vprokru,Пакет,Пятёрочка Налету,5пост'},
           {'id': 191, 'code': 'vh', 'name': 'Штолле', 'search_names': 'Штолле'},
           {'id': 192, 'code': 'qp', 'name': 'Максавит', 'search_names': 'Максавит'},
           {'id': 193, 'code': 'ai', 'name': 'CELEBe', 'search_names': 'CELEBe'},
           {'id': 194, 'code': 'aw', 'name': 'Taikang', 'search_names': 'Taikang'},
           {'id': 195, 'code': 'ahk', 'name': 'БлинБери', 'search_names': 'БлинБери'},
           {'id': 196, 'code': 'ee', 'name': 'Twilio', 'search_names': 'Twilio'},
           {'id': 197, 'code': 'gz', 'name': 'LYKA', 'search_names': 'LYKA'},
           {'id': 198, 'code': 'abw', 'name': 'SOKOLOV', 'search_names': 'SOKOLOV'},
           {'id': 199, 'code': 'kz', 'name': 'NimoTV', 'search_names': 'NimoTV'},
           {'id': 200, 'code': 'afu', 'name': 'ВсеИнструменты', 'search_names': 'ВсеИнструменты'},
           {'id': 201, 'code': 'ajl', 'name': 'av100pro', 'search_names': 'av100pro'},
           {'id': 202, 'code': 'acn', 'name': 'Radium', 'search_names': 'Radium'},
           {'id': 203, 'code': 'acw', 'name': 'YouDo', 'search_names': 'YouDo'},
           {'id': 204, 'code': 'pw', 'name': 'SellMonitor', 'search_names': 'SellMonitor'},
           {'id': 205, 'code': 'vp', 'name': 'Kwai', 'search_names': 'Kwai'},
           {'id': 206, 'code': 'fx', 'name': 'PGbonus', 'search_names': 'PGbonus,пгбонус,зпищтгы'},
           {'id': 207, 'code': 'adv', 'name': 'Cian', 'search_names': 'Cian'},
           {'id': 208, 'code': 'gk', 'name': 'AptekaRU', 'search_names': 'AptekaRU'},
           {'id': 209, 'code': 'ov', 'name': 'Beget', 'search_names': 'Beget'},
           {'id': 210, 'code': 'bm', 'name': 'MarketGuru', 'search_names': 'MarketGuru'},
           {'id': 211, 'code': 'ls', 'name': 'Careem', 'search_names': 'Careem,карим,сфкууь,rfhbv'},
           {'id': 212, 'code': 'zo', 'name': 'Kaggle', 'search_names': 'Kaggle'},
           {'id': 213, 'code': 've', 'name': 'Dream11', 'search_names': 'Dream11'},
           {'id': 214, 'code': 'ct', 'name': 'КухняНаРайоне', 'search_names': 'КухняНаРайоне'},
           {'id': 215, 'code': 'aej', 'name': 'Autoru', 'search_names': 'Autoru'},
           {'id': 216, 'code': 'dp', 'name': 'ProtonMail', 'search_names': 'ProtonMail,протон мейл,зкщещт,ghjnjy'},
           {'id': 217, 'code': 'cn', 'name': 'Fiverr', 'search_names': 'Fiverr'},
           {'id': 218, 'code': 'kh', 'name': 'Bukalapak', 'search_names': 'Bukalapak'},
           {'id': 219, 'code': 'aie', 'name': 'Фотострана', 'search_names': 'Фотострана'},
           {'id': 220, 'code': 'mv', 'name': 'Fruitz', 'search_names': 'Fruitz'},
           {'id': 221, 'code': 'lx', 'name': 'DewuPoison', 'search_names': 'DewuPoison'},
           {'id': 222, 'code': 'kk', 'name': 'Idealista', 'search_names': 'Idealista'},
           {'id': 223, 'code': 'vz', 'name': 'Hinge', 'search_names': 'Hinge'},
           {'id': 224, 'code': 'nv', 'name': 'Naver', 'search_names': 'Naver,yfdth,навер,тфмук'},
           {'id': 225, 'code': 'li', 'name': 'Baidu', 'search_names': 'Baiduбайду'},
           {'id': 226, 'code': 'sn', 'name': 'OLX', 'search_names': 'OLXолх,оликс,jk'},
           {'id': 227, 'code': 'yw', 'name': 'Grindr', 'search_names': 'Grindr,гриндер,uhbylth,пкштвук'},
           {'id': 228, 'code': 'ew', 'name': 'Nike', 'search_names': 'Nike,yfqr,найк,тфйл'},
           {'id': 229, 'code': 'kt', 'name': 'KakaoTalk',
            'search_names': 'KakaoTalk,какаотолк,какао толк,rfrfj,rfrfjnjkr'},
           {'id': 230, 'code': 'yl', 'name': 'Yalla', 'search_names': 'Yallaнфддф,zllf'},
           {'id': 231, 'code': 'mj', 'name': 'Zalo', 'search_names': 'Zalo'},
           {'id': 232, 'code': 'df', 'name': 'Happn', 'search_names': 'Happn'},
           {'id': 233, 'code': 'zh', 'name': 'Zoho', 'search_names': 'Zoho,зохо,ящрщ,pjho'},
           {'id': 234, 'code': 'vm', 'name': 'OkCupid', 'search_names': 'OkCupid'},
           {'id': 235, 'code': 'mo', 'name': 'Bumble', 'search_names': 'Bumble'},
           {'id': 236, 'code': 'xk', 'name': 'DiDi', 'search_names': 'DiDiдиди'},
           {'id': 237, 'code': 'za', 'name': 'JDcom', 'search_names': 'JDcom'},
           {'id': 238, 'code': 'nt', 'name': 'Sravni', 'search_names': 'Sravni'},
           {'id': 239, 'code': 'yu', 'name': 'Xiaomi', 'search_names': 'Xiaomi'},
           {'id': 240, 'code': 'gp', 'name': 'Ticketmaster',
            'search_names': 'Ticketmaster,тикетмастер,ешслуеьфыеук,nbrtnvfcnth'},
           {'id': 241, 'code': 'ns', 'name': 'Oldubil', 'search_names': 'Oldubil'},
           {'id': 242, 'code': 'ho', 'name': 'Cathay', 'search_names': 'Cathay'},
           {'id': 243, 'code': 'wc', 'name': 'Craigslist', 'search_names': 'Craigslist'},
           {'id': 244, 'code': 'og', 'name': 'Okko', 'search_names': 'Okko'},
           {'id': 245, 'code': 'wz', 'name': 'FoxFord', 'search_names': 'FoxFord'},
           {'id': 246, 'code': 'an', 'name': 'Adidas', 'search_names': 'Adidas'},
           {'id': 247, 'code': 'dd', 'name': 'CloudChat', 'search_names': 'CloudChat'},
           {'id': 248, 'code': 'gm', 'name': 'Mocospace', 'search_names': 'Mocospaceмоноспейс'},
           {'id': 249, 'code': 'wp', 'name': '163СOM', 'search_names': '163СOM'},
           {'id': 250, 'code': 'vd', 'name': 'Betfair', 'search_names': 'Betfair'},
           {'id': 251, 'code': 'aed', 'name': 'Kamatera', 'search_names': 'Kamatera'},
           {'id': 252, 'code': 'cr', 'name': 'TenChat', 'search_names': 'TenChat'},
           {'id': 253, 'code': 'gw', 'name': 'CallApp', 'search_names': 'CallApp'},
           {'id': 254, 'code': 'ow', 'name': 'RegRu', 'search_names': 'RegRu'},
           {'id': 255, 'code': 'lt', 'name': 'BitClout', 'search_names': 'BitClout'},
           {'id': 256, 'code': 'zx', 'name': 'CommunityGaming', 'search_names': 'CommunityGaming'},
           {'id': 257, 'code': 'aee', 'name': 'Amway', 'search_names': 'Amway'},
           {'id': 258, 'code': 'jo', 'name': 'SticPay', 'search_names': 'SticPay'},
           {'id': 259, 'code': 'rn', 'name': 'neftm', 'search_names': 'neftm'},
           {'id': 260, 'code': 'tl', 'name': 'Truecaller', 'search_names': 'Truecaller,nherjkkth,труколлер,екгусфддук'},
           {'id': 261, 'code': 'abd', 'name': 'BeeBoo', 'search_names': 'BeeBoo'},
           {'id': 262, 'code': 'akb', 'name': 'Gurmanika', 'search_names': 'Gurmanika'},
           {'id': 263, 'code': 'abl', 'name': 'gpnbonus', 'search_names': 'gpnbonus'},
           {'id': 264, 'code': 'mi', 'name': 'Zupee', 'search_names': 'Zupee'},
           {'id': 265, 'code': 'kj', 'name': 'YAPPY', 'search_names': 'YAPPY'},
           {'id': 266, 'code': 'po', 'name': 'premium.one',
            'search_names': 'premium.one,зкуьшгь,ghtvbev,премиум,premierone,premier'},
           {'id': 267, 'code': 'pv', 'name': 'Koshelek', 'search_names': 'Koshelek'},
           {'id': 268, 'code': 'ajb', 'name': 'Бери заряд', 'search_names': 'Бери заряд'},
           {'id': 269, 'code': 'et', 'name': 'Clubhouse', 'search_names': 'Clubhouseклабхаус'},
           {'id': 270, 'code': 'kd', 'name': 'Author24', 'search_names': 'Author24'},
           {'id': 271, 'code': 'nq', 'name': 'Trip', 'search_names': 'Trip'},
           {'id': 272, 'code': 'at', 'name': 'Perfluence', 'search_names': 'Perfluence'},
           {'id': 273, 'code': 'aef', 'name': 'Велобайк', 'search_names': 'Велобайк'},
           {'id': 274, 'code': 'jf', 'name': 'Likee', 'search_names': 'Likee'},
           {'id': 275, 'code': 'aid', 'name': 'Kia', 'search_names': 'Kia'},
           {'id': 276, 'code': 'amk', 'name': 'GORDAN', 'search_names': 'GORDAN'},
           {'id': 277, 'code': 'ami', 'name': 'TEAMORU', 'search_names': 'TEAMORU'},
           {'id': 278, 'code': 'amy', 'name': 'Отзовик', 'search_names': 'Отзовик'},
           {'id': 279, 'code': 'amx', 'name': 'TANK', 'search_names': 'TANK'},
           {'id': 280, 'code': 'ahc', 'name': 'START', 'search_names': 'START'},
           {'id': 281, 'code': 'gs', 'name': 'SamsungShop', 'search_names': 'SamsungShop'},
           {'id': 282, 'code': 'fs', 'name': ' Şikayet var', 'search_names': ' Şikayet var'},
           {'id': 283, 'code': 'abk', 'name': 'GMX', 'search_names': 'GMX'},
           {'id': 284, 'code': 'yq', 'name': 'mail.com', 'search_names': 'mail.com'},
           {'id': 285, 'code': 'agu', 'name': 'Marlboro ', 'search_names': 'Marlboro '},
           {'id': 286, 'code': 'ael', 'name': 'Cloud Manager', 'search_names': 'Cloud Manager'},
           {'id': 287, 'code': 'qh', 'name': 'Oriflame', 'search_names': 'Oriflame'},
           {'id': 288, 'code': 'aeu', 'name': 'TheFork', 'search_names': 'TheFork'},
           {'id': 289, 'code': 'ajd', 'name': 'Bankera', 'search_names': 'Bankera'}]

ordered_list = services = [
    "Вконтакте",
    "Whatsapp",
    "Viber",
    "Discord",
    "Twitch",
    "Банки",
    "Blizzard",
    "Faceit",
    "FunPay",
    "TikTok/Douyin",
    "Telegram",
    "Snapchat",
    "Facebook",
    "LinkedIN",
    "Instagram+Threads",
    "Одноклассники",
    "Badoo",
    "BIGO LIVE",
    "Tinder",
    "LoveRu",
    "МирЗнакомств",
    "Mylove",
    "AliExpress",
    "Яндекс",
    "KIO",
    "Google",
    "Netflix",
    "eBay",
    "PayPal",
    "Familia",
    "Payoneer",
    "Yahoo",
    "Skype",
    "Microsoft",
    "YouTube",
    "RuTube",
    "Gmail",
    "Mail.ru",
    "Wildberries",
    "OZON",
    "Steam",
    "Юла",
    "Avito",
    "Boosty",
    "Drom",
    "СберМегаМаркет",
    "hh",
    "Почта России",
    "Эльдорадо",
    "IVI",
    "Самокат",
    "Аптека Апрель",
    "СберАптека",
    "Лэтуаль",
    "Sunlight",
    "Metro",
    "LUKOIL-AZS",
    "Детский мир",
    "Apple",
    "X5ID",
    "Burger King",
    "Вкусно и Точка",
    "Dodopizza",
    "CoffeeLike",
    "Окей",
    "Dominos Pizza",
    "Шоколадница",
    "Магнит",
    "МВидео",
    "Maxim",
    "СпортМастер",
    "Lenta",
    "Lamoda",
    "Uralairlines",
    "Rbt",
    "BlaBlaCar",
    "ВкусВилл",
    "Uber",
    "Ашан",
    "MTS CashBack",
    "Twitter",
    "Alipay/Alibaba/1688",
    "KFC",
    "Rambler",
    "Amazon",
    "WeChat",
    "Mamba",
    "CDEK",
    "Bolt",
    "Delivery Club",
    "IQOS",
    "MEGA",
    "Wink",
    "Airbnb",
    "РСА",
    "myGLO",
    "MeetMe",
    "Uteka",
    "Weibo",
    "EscapeFromTarkov",
    "Tencent QQ",
    "Профи",
    "Pivko24",
    "KazanExpress",
    "Line messenger",
    "inDriver",
    "Tango",
    "Dostavista",
    "GalaxyChat",
    "ТОКИО-CITY",
    "Bilibili",
    "icq",
    "УлыбкаРадуги",
    "Wise",
    "RedBook",
    "Рив Гош",
    "Signal",
    "AOL",
    "Namars",
    "urent/jet/RuSharing",
    "constitutioner",
    "СушиВёсла",
    "Ollis",
    "VFS GLOBAL",
    "BRO",
    "BusyFly",
    "Podeli",
    "LigaPro",
    "Things",
    "iQIYI",
    "ЗдравСити",
    "DIKIDI",
    "nloto",
    "米画师Mihuashi",
    "Ортека",
    "Brevo",
    "МИГРАНТ СЕРВИС",
    "LadyMaria",
    "Yami",
    "Notifire",
    "Citymobil",
    "Zolushka",
    "Ximalaya",
    "Expressmoney",
    "SpaceWeb",
    "EnerGO",
    "ZaleyCash",
    "SynotTip",
    "Amasia",
    "Утконос",
    "Karusel",
    "Belwest",
    "Кузбасс Онлайн",
    "FarPost",
    "炙热星河",
    "UU163",
    "Bitrue",
    "MonetaRu",
    "Золотое Яблоко",
    "Голос",
    "Joyride",
    "Stormgain",
    "Энергобум",
    "Weverse",
    "TopDetal",
    "Zdorov",
    "Flowwow",
    "FreshKarta",
    "Домовой",
    "Switips",
    "Hermes",
    "MyLavash",
    "Лейка",
    "YouStar",
    "Vsesmart",
    "mosru",
    "TamTam",
    "Кораблик",
    "Megogo",
    "勇仕网络Ys4fun",
    "Huya",
    "PrivetMir",
    "PingCode",
    "Джилекс",
    "Sorare",
    "Consultant",
    "Uzum",
    "Royal Canin",
    "AptekiPlus",
    "Около",
    "Штолле",
    "Максавит",
    "CELEBe",
    "Taikang",
    "БлинБери",
    "Twilio",
    "LYKA",
    "SOKOLOV",
    "NimoTV",
    "ВсеИнструменты",
    "av100pro",
    "Radium",
    "YouDo",
    "SellMonitor",
    "Kwai",
    "PGbonus",
    "Cian",
    "AptekaRU",
    "Beget",
    "MarketGuru",
    "Careem",
    "Kaggle",
    "Dream11",
    "КухняНаРайоне",
    "Autoru",
    "ProtonMail",
    "Fiverr",
    "Bukalapak",
    "Фотострана",
    "Fruitz",
    "DewuPoison",
    "Idealista",
    "Hinge",
    "Naver",
    "Baidu",
    "OLX",
    "Grindr",
    "Nike",
    "KakaoTalk",
    "Yalla",
    "Zalo",
    "Happn",
    "Zoho",
    "OkCupid",
    "Bumble",
    "DiDi",
    "JDcom",
    "Sravni",
    "Xiaomi",
    "Ticketmaster",
    "Oldubil",
    "Cathay",
    "Craigslist",
    "Okko",
    "FoxFord",
    "Adidas",
    "CloudChat",
    "Mocospace",
    "163СOM",
    "Betfair",
    "Kamatera",
    "TenChat",
    "CallApp",
    "RegRu",
    "BitClout",
    "CommunityGaming",
    "Amway",
    "SticPay",
    "neftm",
    "Truecaller",
    "BeeBoo",
    "Gurmanika",
    "gpnbonus",
    "Zupee",
    "YAPPY",
    "premium.one",
    "Koshelek",
    "Бери заряд",
    "Clubhouse",
    "Author24",
    "Trip",
    "Perfluence",
    "Велобайк",
    "Likee",
    "Kia",
    "GORDAN",
    "TEAMORU",
    "Отзовик",
    "TANK",
    "START",
    "SamsungShop",
    "Şikayet var",
    "GMX",
    "mail.com",
    "Marlboro",
    "Cloud Manager",
    "Oriflame",
    "TheFork",
    "Bankera"
]
