API_TOKEN: ''

DB_HOST: ''
DB_PORT: 5432
DB_USER: ''
DB_NAME: ''
DB_PASS: ''

SMS_ACTIVATE_KEY: ''

LAVA_SHOP_ID: ''
LAVA_SECRET_KEY: ''

FK_SHOP_ID: 
FK_SECRET_KEY: ""

REF_BONUS: 10 # %

WITHDRAW_CHAT_ID: "-"
SUPPORT_URL: ""

ADMINS:
  -  
  - 

CHANNEL_ID: ""
